# A Dockerised Jobe Server
services:
  jobe:
    image: ruseler/jobeinabox:ubuntu
    #image: ruseler/jobeinabox:debian-slim
    #image: ruseler/jobeinabox:latest
    container_name: jobeinabox
    restart: always
    ports:
      - '4000:80'
