# A Dockerised Jobe Server
services:
  jobe:
    image: ruseler/jobeinabox:latest
    #image: trampgeek/jobeinabox:latest
    container_name: jobeinabox
    restart: always
    ports:
      - '4000:80'
